apiVersion: v1
kind: Service
metadata:
  name: maven
  labels:
    app: maven
    group: compiler
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: maven
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: maven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
        group: compiler
    spec:
      containers:        
      - name: maven
        image: maven
        imagePullPolicy: IfNotPresent        
        # Just spin & wait forever
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 8080
          name: maven    
        volumeMounts:
        - mountPath: "/src"
          name: "host-data"
      volumes:
      - name: "host-data"
        hostPath:
         path: "/vagrant"      