apiVersion: v1
kind: Service
metadata:
  name: beakerx
  labels:
    app: beakerx
    group: web
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 32088    
    protocol: TCP
  selector:
    app: beakerx
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: beakerx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beakerx
  template:
    metadata:
      labels:
        app: beakerx
        group: web
        tier: frontend
    spec:
      containers:
      - name: beakerx
        image: beakerx/beakerx
        imagePullPolicy: IfNotPresent
        command: [ "start-notebook.sh", "--NotebookApp.token=''" ]        
        ports:
        - containerPort: 8888
          name: beakerx
        # Volumes im Container
        volumeMounts:
        #- mountPath: "/home/beakerx"
        #  name: "beakerx-data"
        - mountPath: "/usr/bin/docker"
          name: "docker"   
        - mountPath: "/usr/lib/x86_64-linux-gnu/libltdl.so.7"
          name: "libltdl" 
        env:
        - name: DOCKER_HOST
          value: "tcp://dind:2375"                     
      # Volumes in Host
      volumes:
      #- name: "beakerx-data"
      #  hostPath:
      #   path: "/data/beakerx" 
      #   type: DirectoryOrCreate
      - name: "docker"
        hostPath:
         path: "/usr/bin/docker"
      - name: "libltdl"
        hostPath:
         path: "/usr/lib/x86_64-linux-gnu/libltdl.so.7"            