apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: jupyter
    group: web
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 32388    
    protocol: TCP
  selector:
    app: jupyter
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
        group: web
        tier: frontend
    spec:
      containers:
      - name: jupyter
        image: jupyter/base-notebook
        imagePullPolicy: IfNotPresent
        command: [ "start-notebook.sh", "--NotebookApp.token=''" ]        
        ports:
        - containerPort: 8888
          name: jupyter
        # Volumes im Container
        volumeMounts:
        - mountPath: "/home/jovyan/work"
          name: "jupyter-data"
        - mountPath: "/usr/bin/docker"
          name: "docker"   
        - mountPath: "/usr/lib/x86_64-linux-gnu/libltdl.so.7"
          name: "libltdl" 
        env:
        - name: DOCKER_HOST
          value: "tcp://dind:2375"                     
      # Volumes in Host
      volumes:
      - name: "jupyter-data"
        hostPath:
         path: "/data/jupyter" 
         type: DirectoryOrCreate
      - name: "docker"
        hostPath:
         path: "/usr/bin/docker"
      - name: "libltdl"
        hostPath:
         path: "/usr/lib/x86_64-linux-gnu/libltdl.so.7"            