apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
spec:
  ports:
    - port: 8080
  selector:
    app: microservice-kubernetes-demo-customer
    tier: microservice
  clusterIP: None
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: microservice-kubernetes-demo-customer
  labels:
    app: microservice-kubernetes-demo-customer
spec:
  selector:
    matchLabels:
      app: microservice-kubernetes-demo-customer
      tier: microservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: microservice-kubernetes-demo-customer
        tier: microservice
    spec:
      containers:
      - name: microservice-kubernetes-demo-customer
        image: microservice-kubernetes-demo-customer
        imagePullPolicy: IfNotPresent    
        ports:
        - containerPort: 8080
          name: customer